---
- name: Converge
  hosts: {{ cookiecutter.role_name | replace("_", "-") }}-test-control-plane
  connection: docker
  gather_facts: false
  roles:
    - role: {{ cookiecutter.namespace }}.{{ cookiecutter.role_name }}
...
