---
- name: Verify
  hosts: {{ cookiecutter.role_name }}-test-control-plane
  connection: docker
  gather_facts: false
  tasks:
    - name: Check executor dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
        state: present
      check_mode: true
      register: {{ cookiecutter.role_name }}_verify
      failed_when: {{ cookiecutter.role_name }}_verify.changed

    - name: Check ansible dependencies
      ansible.builtin.pip:
        name:
          - kubernetes
          - openshift
          - pyyaml
      check_mode: true
      register: {{ cookiecutter.role_name }}_verify
      failed_when: {{ cookiecutter.role_name }}_verify.changed

    - name: Check namespace
      kubernetes.core.k8s:
        name: "default"
        api_version: v1
        kind: Namespace
        state: present
      check_mode: true
      register: {{ cookiecutter.role_name }}_verify
      failed_when: {{ cookiecutter.role_name }}_verify.changed
...
