---
- name: Verify
  hosts: {{ cookiecutter.role_name | replace("_", "-") }}-test-control-plane
  connection: docker
  gather_facts: false
  tasks:
    - name: Check executor dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
        state: present
      check_mode: true
      register: {{ cookiecutter.role_name }}_verify
      failed_when: {{ cookiecutter.role_name }}_verify.changed

    - name: Check ansible dependencies
      ansible.builtin.pip:
        name:
          - kubernetes
          - openshift
          - pyyaml
      check_mode: true
      register: {{ cookiecutter.role_name }}_verify
      failed_when: {{ cookiecutter.role_name }}_verify.changed

    - name: Check helm key is added to apt
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present
      check_mode: true
      register: {{ cookiecutter.role_name }}_verify
      failed_when: {{ cookiecutter.role_name }}_verify.changed

    - name: Check helm repo has been added to apt
      ansible.builtin.apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
      check_mode: true
      register: {{ cookiecutter.role_name }}_verify
      failed_when: {{ cookiecutter.role_name }}_verify.changed

    - name: Check that helm is installed
      ansible.builtin.apt:
        name:
          - helm
        state: present
      check_mode: true
      register: {{ cookiecutter.role_name }}_verify
      failed_when: {{ cookiecutter.role_name }}_verify.changed

    - name: Check namespace
      kubernetes.core.k8s:
        name: "default"
        api_version: v1
        kind: Namespace
        state: present
      check_mode: true
      register: {{ cookiecutter.role_name }}_verify
      failed_when: {{ cookiecutter.role_name }}_verify.changed
...
